model:
  model_name: "qwen7b"
  model_path: "/data/yyma/code/models/Qwen2.5-7B-Instruct"
  encoder_name: "bert"
  encoder_path: "/data/yyma/code/models/bert-base-cased"

data:
  set_name: "ontonotes"
seed: 2026

stage:
  pre_filter: false
  train: false
  test: true